### ISSUE TITLE
Proposal: make Chroma.js immutable

### ISSUE THREAD

**Issue by yuchi** [gka/chroma.js#100]
This is something I’ve been thinking on for a long time but could actually implement it by myself.

Given how immutable data structures are gaining traction it would be awesome to have chroma.js offer purely immutable alternatives.

What do you think about it?

**Comment by Qix-** [comment]
Not to plug color.js, but we had a similar request over at that lib a while back. There is a lot to be gained from immutable structures; I know quite a few libs use chroma.js and I'm sure they'd benefit.

**Comment by tehnomaag** [comment]
Hear hear! It would be very beneficial if every api call would return a new immutable color instance.

Also, easy serialization/deserialization (via JSON.stringify/parse) would be nice. We're using chroma-js in a design-oriented tool and have a need to persist tool settings (including color state) in localStorage.

**Comment by gka** [comment]
**serialization/deserialization:**

chroma.js stores all colors as rgb internally. persistent storage of a chroma instance is as simple as storing the color's hex code. the easiest way to do this is to convert the color to a string:

```js
var color = chroma(..);
s = color.toString(); // or
s = String(color);  // or
s = '' + color;
```

the returned value can be converted back to a chroma.js "instance" by simply passing it to the chroma constructor:

```js
color = chroma(s);
```

So there's no need for JSON serialization.

**Comment by JakeCoxon** [comment]
This is a great library but strange api. chroma.darken returns a new instance but chroma.alpha doesn't. And `chroma(prevColor).alpha(0.5)` mutates the original `prevColor`. Adding a clone method would help the pain a bit

**Comment by gka** [comment]
Agree, this shouldn't happen. Will fix that in the next release.

One work-around is to string-serialize before passing prevColor to the chroma constructor. 

```js
chroma('' + prevColor).alpha(0.5);
```

**Comment by natew** [comment]
Any progress on this? Haven't looked at code but could help with this quickly, as it's a dealbreaker for us to use and should be simple change, theoretically.

**Comment by StreetStrider** [comment]
@gka,
> the easiest way to do this is to convert the color to a string

not quite well in cases when alpha is different than `1`. I personally use magic spell `Chroma(color.rgba())` to clone color.
Agreed with @JakeCoxon that `clone` method would be helpful. Moreover, `clone` is crucial in case of an in-place mutable API, like Chroma.

**Comment by gka** [comment]
btw, I changed `chroma.alpha` so that it returns a new instance, see this test:
https://github.com/gka/chroma.js/blob/master/test/alpha-test.coffee#L112-L116

I *think* there should be no cases left where chroma function mutate the internal color instead of returning a new instance...
