### ISSUE TITLE
chroma.lch() with l=0 is not black

### ISSUE THREAD

**Issue by gson1703** [gka/chroma.js#102]
I would expect an LCH color with a lightness of 0 to be black, but it isn't.
For example, chroma.lch(0, 50, 50) yields #370000, not #000000.

**Comment by gka** [comment]
no, in LCH, black is defined as the absence of both lightness and "colorfulness". if you want black, you must not mix any color in. with L=0 and C=50, you are not asking for black but for the darkest half-saturated color. 

I guess what you want is HSL:
```js
chroma.hsl(50,0.5,0) // "#000000"
```
