### ISSUE TITLE
Quantiles broken on scale domains

### ISSUE THREAD

**Issue by levitanong** [gka/chroma.js#103]
https://github.com/gka/chroma.js/wiki/Color-Scales#data-specific-color-scales

> For more advanced techniques you need the actual dataset
> 
> ``` js
> chroma.scale(['#eee', '#900']).domain(values, 5, 'quantiles');
> chroma.scale(['#eee', '#900']).domain(values, 5, 'k-means');
> ```

I've also taken a look at the source, and it doesn't seem like `.domain` supports quantiles.

**Comment by gka** [comment]
the API for this has changed slightly. 

```js
// create six nice colors in between gray and red
var colors = chroma.scale(['#eee', '#900']).mode('lch').colors(6);
// compute the positions for the colors
var breaks = chroma.limits(values, 5, 'quantiles');
// create a scale using colors and breaks
chroma.scale(colors).domain(breaks);
```
guess this could be simplified
