### ISSUE TITLE
Cubehelix breaks when both lightness values are the same

### ISSUE THREAD

**Issue by davidjohnstone** [gka/chroma.js#105]
Using the Chrome console:

```
> chroma.cubehelix().lightness([0.5, 0.49])(0.2).hex()
"#518ea9"
> chroma.cubehelix().lightness([0.5, 0.5])(0.2).hex()
"#000000"
> chroma.cubehelix().lightness([0.5, 0.51])(0.2).hex()
"#528faa"
```

The problem seems to be that `cubehelix.coffee:84`, `lightness = lightness[1] if dl == 0`, is not necessary, and just breaks it by changing `lightness` to a number instead of an array. Setting the lightness in the constructor avoids this problem.

**Comment by gka** [comment]
fixed in version 1.3.0
