### ISSUE TITLE
Hue direction of linear interpolation in lch .

### ISSUE THREAD

**Issue by andaja** [gka/chroma.js#108]
Currently, if I state 
chroma.interpolate('#003157', '#FF9D29', i / c, 'lch');
chroma.js will interpolate using the shortest route which in the example above runs through red part of the spectrum. Is it possible to state the preferable direction (clockwise or counterclockwise), so the example above goes through green part?

**Comment by gka** [comment]
I think you'd have to insert one or two colors in between in order to force your way around the long part of the circle
```js
chroma.scale([
   chroma.lch(60,90, 0),
   chroma.lch(60,90, 120),
   chroma.lch(60,90, 240),
   chroma.lch(60,90, 360),
])
```
