### ISSUE TITLE
Lab -> RGB returns negative zero

### ISSUE THREAD

**Issue by fdietze** [gka/chroma.js#109]
This code returns a negative zero, which does not make sense in RGB color space.

``` javascript
chroma.lab(0,-120,-2).rgb()[2]
```

**Comment by cornerman** [comment]
This is straightforward in javascript:
```("" + -0) - 0```
:D

**Comment by gka** [comment]
I didn't even know there was a negative zero in JS. how does this "break" any use case? you know that `-0 === 0`, right?

**Comment by gka** [comment]
this is fixed now
