### ISSUE TITLE
Last number in limit is smaller than the rest

### ISSUE THREAD

**Issue by reyemtm** [gka/chroma.js#111]
I opened this issue at [leaflet-choropleth](https://github.com/timwis/leaflet-choropleth/issues/13), but that uses chroma so thought I would mention here as well. Hope someone can point me in the right direction.

I have six json files using the chroma/choropleth plugin, with mode: 'q', and for two of them the last limit number is smaller than the rest.  Still the map draws the right colors. Not sure if it is a problem with the data, chroma or leaflet-choropleth. The limit array is written to the console when each layer is drawn on the map. I am working on a pure chroma example to see if I can further pinpoint the issue.

```
["10065", 20996.75, 24371, 28654.5, "8924"] OR
["10172", "18263", "21779", "27054", "9815"] - 9815 should be 148729 in this case
```

Ideas? 

[Map](https://www.ovrdc.org/apps/demographic-explorer.html)

**Comment by gka** [comment]
think this is fixed now
