### ISSUE TITLE
The for...in in `_input.rgb` will make the rgb value become unsafe when people overwrite the Array.prototype

### ISSUE THREAD

**Issue by jwu** [gka/chroma.js#113]
Hi,

Recently I found a problem relate with the code: https://github.com/gka/chroma.js/blob/master/chroma.js#L807.

When people overwrite an Array.prototype such as:

``` js
Array.prototype.indexOf = ...
```

The `ref` will return an Array which will include the `indexOf` method since `for...in` didn't filter out the `indexOf` function by `hasOwnProperty` method.

**Comment by waldyrious** [comment]
IIRC this is solved by using `for...of` instead of `for...in`.

**Comment by gka** [comment]
I don't think chroma.js should deal with scenarios in which people overwrite core JS class prototypes. for instance, when someone decides to overwrite `Math.round` like this, chroma.js would break as well:
```js
> Math.round = function(d) { return d*2; };
> Math.round(3.4)
6.8
```
there is no way to prevent that.
