### ISSUE TITLE
Question: how did license switch from GPL to BSD happen?

### ISSUE THREAD

**Issue by sgustafsson** [gka/chroma.js#114]
Hi,

the readme says "Released under BSD license. Versions prior to 0.4 were released under GPL." How was the switch from GPL to BSD performed? Were you the only contributor of source code prior version 0.4 (and hence the only copyright holder)? If not, did you ask for permission of all other contributors reg. the switch from GPL to BSD?

Best

**Comment by emilv** [comment]
I also wonder this. I went into the Git history and there were three contributors at that time:

* @gka Package author/maintainer
* @KrofDrakula https://github.com/gka/chroma.js/commits/master?author=KrofDrakula
* @rufuspollock https://github.com/gka/chroma.js/commits/master?author=rufuspollock

Does @KrofDrakula and @rufuspollock agree with the license change?

**Comment by KrofDrakula** [comment]
For what it's worth, I give @gka a blank check to do with my contributions to this project as they see fit.

**Comment by gka** [comment]
to answer this question: nope, I didn't ask the other two contributors. but as you see from the commits, neither of them at the time had even touched the actual source code of the library.
