### ISSUE TITLE
What are the input ranges for LCH?

### ISSUE THREAD

**Issue by jameshfisher** [gka/chroma.js#115]
Looking at http://gka.github.io/chroma.js/#color-lch I see

> L: Lightness, c: chroma (0-1), h: hue (0-1).
> Example: `chroma.lch(80, 40, 130);`

These seem to contradict each other: passing in values of `40` and `130` for parameters which should be in the range `0-1`?

Which should it be? And what is the range for the `L` parameter?

**Comment by gka** [comment]
fixed

**Comment by waldyrious** [comment]
For future reference, this was a dupe of #85.
