### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by callumacrae** [gka/chroma.js#119]
Hello!

I'm using chroma.js as part of a parallax effect, and it's currently the slowest thing in the effect (not a bad thing: everything else is super light).

Have you got any tips for making it more performant? I'm using a scale which has been initialised outside the loop, so it's basically doing this:

```js
const scale = chroma.scale(['red', 'black']).mode('lab');

function frame() {
  scale(0.5).hex();
}
```

Is there a more efficient way of doing this?

Thanks for chroma.js 😃

**Comment by gka** [comment]
well the only thing that comes to mind is to pre-compute the colors and/or load them from cache. or you can compute a couple of colors from the Lab gradient and create a new `rgb` scale that is probably a little bit faster...
