### ISSUE TITLE
Guarantee input colors present in output

### ISSUE THREAD

**Issue by joeveiga** [gka/chroma.js#122]
Hi there. Wondering if there is a way to guarantee that the colors used as input to `chroma.scale(inputColors)` can be found in the output of something like this: 

`var outputColors = chroma.scale(inputColors).colors(inputColors.length * 2 + 1);`

Basically what we want to do is double our color range, but we need to keep the original colors in the extended version.

Thanks!

**Comment by gka** [comment]
questions should better be asked on stackoverflow.

but to make sure you got the same colors in the output you would need `input.length * 2 - 1`
