### ISSUE TITLE
chroma.limits for quantiles broken for edge-cases

### ISSUE THREAD

**Issue by dts-ait** [gka/chroma.js#123]
The chrome.limits function seems to be buggy regarding small and uniform data sets.

In these examples NaNs are present in the bounds:

`chroma.limits([1], 'q', 5)`
> Array [ 1, NaN, NaN, NaN, NaN, 1 ]

`chroma.limits([1,1], 'q', 5)`
> Array [ 1, 1, 1, NaN, NaN, 1 ]

In this example in addition to the NaNs the order of the bounds is invalid - first 0.6 and then 0.199:
`chroma.limits([0,1], 'q', 5)`
> Array [ 0, 0.6, 0.19999999999999996, NaN, NaN, 1 ]

**Comment by gka** [comment]
well, it surely looks broken, but this operations does not make any sense whatsoever. to compute proper quantiles, you need more values. but I guess the function should just throw a proper error instead of NaNs.

**Comment by dts-ait** [comment]
Of course more diverse data is required for proper quantiles, but in my use case I do not know how diverse my input dataset is and it would be nice to have a defined behaviour in such edge cases - not necessarily an error.
E.g.:
`chroma.limits([1], 'q', 5)`
> Array [ 1, 1, 1, 1, 1, 1 ]

`chroma.limits([0,1], 'q', 5)`
> Array [ 0, 0.2, 0.4, 0.6, 0.8, 1 ]

**Comment by gka** [comment]
fixed
