### ISSUE TITLE
Scale with 1 color always returns '#cccccc'

### ISSUE THREAD

**Issue by steadicat** [gka/chroma.js#125]
When you request one color from a scale, for some reason Chroma always returns gray. It would make more sense for Chroma to pick the starting point or the mid point of the scale.

![image](https://cloud.githubusercontent.com/assets/6031/24113318/a71f0c60-0d59-11e7-805b-11b3c00ad0fd.png)

**Comment by dmcclory** [comment]
This caught my eye & looked kinda easy so I dug in.

It's happening [in the `scale.colors` method]. The only place in the code that refers to `#cccccc` is a line that sets `_nacol = chroma '#ccc'`. And the only method that uses it is [getColor](https://github.com/gka/chroma.js/blob/master/src/scale.coffee#L66-L67):

```
getColor = (val, bypassMap=false) ->
    if isNaN(val) then return _nacol
```

When the numColors is 1, it ends up passing `NaN` to `f`, which calls `getColor`:

This happens in [scale.colors](https://github.com/gka/chroma.js/blob/master/src/scale.coffee#L229-L232):

```
if numColors
    dm = _domain[0]
    dd = _domain[1] - dm
    return [0...numColors].map (i) -> f( dm + i/(numColors-1) * dd )[out]()
```

If you're interested, I could put up a PR. I agree that it makes sense to return the midpoint of the scale.

**Comment by gka** [comment]
fixed
