### ISSUE TITLE
perceptual color difference

### ISSUE THREAD

**Issue by Offirmo** [gka/chroma.js#127]
Hello and thanks for your great lib !

I'm generating scales of colors to be displayed on a light grey background.

Since I don't want the generated colors to be hard to differentiate from the background, I'm filtering them by their "closeness" to the background color.

The only way I found so far was to use the "contrast(a, b)" function, but it doesn't work that well perceptually. For example, for a same minimum contrast, the yellow color it a lot closer to the light grey than the blue color.

Researching color difference, I saw here http://stackoverflow.com/questions/9018016/how-to-compare-two-colors some suggestions about using delta-E.

Does it exist in chroma ? If not, wouldn't it be a nice addition ?

**Comment by gka** [comment]
yes, deltaE is a useful addition. I will add it! thanks.

**Comment by Offirmo** [comment]
amazing! can't wait!

**Comment by gka** [comment]
just realized there is an actual JS implementation on the website that I should probably use instead of typing in the formula

**Comment by Offirmo** [comment]
I applaude your efforts

**Comment by gka** [comment]
added to version 1.3.0

**Comment by Offirmo** [comment]
I tested your new function, and I agree that the results are strange.

1) the reflexivity problem you mentioned is suspicious.
2) the results I get in my case are mixed. It's not really better than checking the contrast, even when it should

I'll try to tinker a bit.

**Comment by Offirmo** [comment]
The Lab deltaE is reflexive and easy to apprehend:

```typescript
function color_difference(ref_color: string, test_color: string): number {
	const [ L1, a1, b1 ] = chroma(ref_color).lab()
	const [ L2, a2, b2 ] = chroma(test_color).lab()

	return Math.sqrt( Math.pow(L2 - L1, 2) + Math.pow(a2 - a1, 2) + Math.pow(b2 - b1, 2) )
}
```

**Comment by Offirmo** [comment]
I also tried the CIE94 from the wikipedia formulas:

```typescript
// CIE94
// https://en.wikipedia.org/wiki/Color_difference#CIE94
function color_difference(ref_color: string, test_color: string): number {
	const [ L1, a1, b1 ] = chroma(ref_color).lab()
	const [ L2, a2, b2 ] = chroma(test_color).lab()

	// values for "graphic arts"
	const kL = 1
	const K1 = 0.045
	const K2 = 0.015
	
	// usual values
	const kC = 1
	const kH = 1

	const deltaEab = Math.sqrt( Math.pow(L2 - L1, 2) + Math.pow(a2 - a1, 2) + Math.pow(b2 - b1, 2) )
	const deltaL = L1 - L2
	const C1 = Math.sqrt( a1 * a1 + b1 * b1)
	const C2 = Math.sqrt( a2 * a2 + b2 * b2)
	const deltaCab = C1 - C2
	const deltaHab = Math.sqrt( deltaEab * deltaEab - deltaL * deltaL - deltaCab * deltaCab)
	
	// control
	const deltaa = a1 - a2
	const deltab = b1 - b2
	const deltaHab2 = Math.sqrt( deltaa * deltaa + deltab * deltab - deltaCab * deltaCab)
	console.assert(Math.trunc(deltaHab * 1000000) === Math.trunc(deltaHab2 * 1000000), 'erreur')
	
	const SL = 1
	const SC = 1 + K1 * C1
	const SH = 1 + K2 * C1

	// parts
	const p1 = deltaL / kL * SL
	const p2 = deltaCab / kC * SC
	const p3 = deltaHab / kH * SH

	return Math.sqrt( p1 * p1 + p2 * p2 + p3 * p3 )
}
```

The result is also not reflexive! (so it's expected)

Results are slightly better than CI76 (esp. for blues)

I'm to lazy to implement the CIEDE2000 which is supposed to be even better.

**Comment by Offirmo** [comment]
Real case: I'm generating random colors from yellow, blue, green, pink and grey, whom I want to be contrasted enough with both the background (white) and the foreground (black)

Using chroma.contrast()
<img width="1045" alt="cd_contrast" src="https://cloud.githubusercontent.com/assets/603503/25797563/20002acc-3421-11e7-8ca5-d0522e4b402d.png">
