### ISSUE TITLE
Why hcl -> rgb does not match rgb -> hcl in the following case?

### ISSUE THREAD

**Issue by rafaveguim** [gka/chroma.js#129]
```javascript
var hex = chroma.hcl(22,80,85).hex();
console.log(chroma(hex).hcl())
// [13.213071650997904, 44.63507243679763, 72.06085283269316]
```

I was expecting the output to be [22,80,85].

**Comment by gka** [comment]
that's because colors from the (smaller) color space RGB can be expressed in more than one way in HCL. 

```js
chroma.hcl(20,80,85).hex();  // == "#ff8fa5"
chroma.hcl(9.32,45.13,71.93).hex();  // == "#ff8fa5"
```
the same is true for some other color spaces. for instance, in CMYK, both of these colors represent `#cccccc` in RGB:

```js
chroma.cmyk(0,0,0,.2);
chroma.cmyk(0.2,0.2,0.2,0);
```
so if you'd go from CMYK to RGB to CMYK the same thing can happen:
```js
chroma(chroma.cmyk(0.2,0.2,0.2,0).hex()).cmyk(); // == [0,0,0,0.2]
```
