### ISSUE TITLE
Clamp colors to domain in chroma.scale?

### ISSUE THREAD

**Issue by VictorVelarde** [gka/chroma.js#130]
Hi there,

I'm using chromajs for a project and I'm wondering if there is a clean way to clamp `chroma.scale` colors at the `domain` limits, returning something such as a `transparent` color if a value lies outside.

Something like having `var scale = chroma.scale(['white', 'black']).domain([0, 100]);` and getting transparent color for values <0 and >100. It could be explicit with something like `.domain([20, 0]).clamp([true, true])` to selectively clamp on each end.

Thanks for your nice work!

**Comment by gka** [comment]
I think it takes so little to wrap a `chroma.scale` into a function that it doesn't justify the amount of code to build this into chroma. some people might not want "transparent" to be the clamped value but rather have the min/max colors, which is also how clamping works in D3.
```js
function clamped_scale(v) { return v < 0 || v > 100 ? 'transparent' : scale(v); }
```

so if I would add `scale.clamp` it would probably work [just like in D3](https://github.com/d3/d3-scale/blob/master/README.md#continuous_clamp).

**Comment by VictorVelarde** [comment]
Fair enough. 
Thx!
