### ISSUE TITLE
Not tiny anymore

### ISSUE THREAD

**Issue by ddfreyne** [gka/chroma.js#132]
The README says

> Chroma.js is a tiny JavaScript library (14kB)

… even though the library is now closer to 37 KB (minified) or 76 KB (not minified).

(Personal opinion: it does not matter so much as to how big a library is, but rather how good it is at its job. Modern minifiers can remove unused parts anyway.)

**Comment by sheley1998** [comment]
I have the same issue. Would love to use chroma in a production website, but the 37kb puts it in the league of monolithic libraries such as jQuery... what is this modern minifier that you speak of?

**Comment by gka** [comment]
chroma.js is 14kB minified + gzip which is the way javascript code is being shipped to users these days.

![image](https://cloud.githubusercontent.com/assets/617518/24827570/b613cb64-1c4c-11e7-91b4-2cbb412234ee.png)

**Comment by gka** [comment]
as comparison, jquery is 29.8kB minified + gzipped, more than twice the size of chroma, and D3.js is 71.9kB (five times as large).
