### ISSUE TITLE
scale.colors(1) returns string, scale.colors(2) returns array

### ISSUE THREAD

**Issue by AdeelK93** [gka/chroma.js#133]
I'm using chroma.js to generate an array of colors to use in charts, with one color for each variable represented. In 1.3.1 and prior versions, scale.colors would always return an array, but in 1.3.3, the return value might be a string or might be an array.

Would it be possible to revert to the old system of the function always returning an array, no matter the input? Thank you so much for your hard work on this package!

**Comment by gka** [comment]
yep, that was an accident. fixed it. thx
