### ISSUE TITLE
Return amount darkened when given two colors

### ISSUE THREAD

**Issue by deecewan** [gka/chroma.js#134]
Hey,

I've had a look and I can't see a way to do it. Essentially, given two colors (a reference, and a current), compute the amount that the `current` has moved away from `reference`, using the darken/brighten functions.

for example, taking `#FFF` as a reference:

- `chroma('#FFF').darken().hex() // #cccccc`

then, using some other call, such as `difference`,

- `chroma.difference('#FFF', '#cccccc') // 1`

or, `chroma('#000').brighten(5).hex() // #e2e2e2`

- `chroma.difference('#000', '#e2e2e2') // -5`

Is this even possible? It'd be super handy.

**Comment by gka** [comment]
if you look at the darken [source code](https://github.com/gka/chroma.js/blob/master/src/ops/darken.coffee#L6) you see that all it does is to subtract the `L` component with a factor `amount * Kn`. the [Kn constant](https://github.com/gka/chroma.js/blob/master/src/converter/misc/lab-constants.coffee#L6) happens to be `18`, so you can compute the darken factor pretty easy:

```js
var l0 = chroma('#fff').get('lab.l'),   // 100.00000
    l1 =  chroma('#888').get('lab.l'),  // 56.70341
    diff = (l0 - l1) / 18;              // 2.40536
chroma('#fff').darken(diff).hex()       // "#888888"
```
