### ISSUE TITLE
chroma domain with no arguments

### ISSUE THREAD

**Issue by gonzalolc** [gka/chroma.js#135]
Hello
I'm trying to obtain (as explained and shown in the wiki) the current domain.

In the wiki it says:

> Calling .domain() with no arguments will return the current domain.
>chroma.scale(['white', 'red']).domain([0, 100], 4).domain() // [0, 25, 50, 75, 100]

but it only returns [0, 100]
How could I get the [0, 25, 50, 75, 100] result?

Thanks

**Comment by gka** [comment]
the documentation has moved to [this website](gka.github.io/chroma.js), the examples in the wiki were outdated.

to answer your question, `scale.domain` will always just return the [min, max] range.
I guess what you want is the [chroma.limits](https://gka.github.io/chroma.js/#chroma-limits) helper function:

```js
chroma.limits([0,100],'e', 4) //  [0, 25, 50, 75, 100] 
```
