### ISSUE TITLE
No way to get 'Color's from Scale.colors(x)

### ISSUE THREAD

**Issue by NaridaL** [gka/chroma.js#136]
Scale.colors doesn't behave in a consistent fashion with plain Scale()

`chroma.scale('red', 'blue').colors(5, false)` should be allowed, as

`chroma.scale('red', 'blue').out(false)(0.5)` works.

Alternatively, colors should just take the `out` from the Scale, e.g. `chroma.scale('red', 'blue').out(false).colors(5)`

**Comment by gka** [comment]
good point, will add this..

**Comment by gka** [comment]
added to version 1.3.4

**Comment by NaridaL** [comment]
Hmm... now `color.scale('red', 'blue').out('rgba')` just fails silently. You probably want `if (out) `, not if `chroma[ou]`.
