### ISSUE TITLE
turn chroma into a proper ES6 module

### ISSUE THREAD

**Issue by gka** [gka/chroma.js#138]
it would be nice if one could just import a few functions and treeshake the rest off with a bundler like rollup.

**Comment by ericmarkmartin** [comment]
I was actually importing chroma with ES6 module syntax in a recent project and had no issues unused code in the bundle (using webpack).

**Comment by larsenwork** [comment]
@ericmarkmartin can you give any pointers to how you did because mine still comes in at 14kb in a webpack setup 🤓

**Comment by jo-m** [comment]
```
import * as chroma from 'chroma-js';
chroma('red').hex();
```

**Comment by Spaxe** [comment]
This would be an ideal feature to have, as `chroma-js` currently doesn't work with `parcel`.

**Comment by flcoder** [comment]
You can convert chroma.min.js:

Add the following to the end of the file

```javascript
export default fn.chroma
function fn() {}
```

Then look for the end where it has `.call(this)` and change it to `.call(fn)`

**Comment by Spaxe** [comment]
That's some level of black magic there @flcoder.

Ideally I'd like to have this work with the ecosystem like `npm` or `yarn`, without monkey patching.

**Comment by gka** [comment]
finally, glad to report this is done! chroma is now es6-only.

**Comment by Spaxe** [comment]
AWESOME!

**Comment by indo-dev-0** [comment]
@gka So tree-shaking actually works?

**Comment by tremby** [comment]
I think it might not. I'm only using two methods on my current project so far, and my bundle got about 15k bigger.
