### ISSUE TITLE
Convenience Method to apply functions to scales (or array of hexes)

### ISSUE THREAD

**Issue by huiguang-liang** [gka/chroma.js#139]
Hi, love chroma.js!

May I suggest that functions that apply to individual colors also apply to scales (or array of hexes)?

For example, rather than having to write something like:
`chroma.scale('spectral').mode('lch').colors(6).map(x -> chroma(x).darken(2))`

It would be nice if we could directly write:
`chroma.scale('spectral').mode('lch').colors(6).darken(2)`

It will be much easier to generate shades of scales, and the code looks cleaner and more intuitive.
(I'm also really lazy and use https://gka.github.io/chroma.js/#quick-start to quickly generate colors in-line ;p)

Thanks for considering this!

**Comment by huiguang-liang** [comment]
I just realized that .colors() would have to itself return a `chroma` object for this to work. If it breaks workflows, we can close this issue.

**Comment by gka** [comment]
I think this works if you provide `null` as second argument to `.colors()`.

```js
chroma.scale('spectral').colors(6, null).map(d => d.darken());
```
