### ISSUE TITLE
Noncommutative chroma#deltaE

### ISSUE THREAD

**Issue by kswilster** [gka/chroma.js#144]
This came as a surprise to me, but the `deltaE` method for determining perceptual distance between colors is not commutative. i.e.
```js
chroma.deltaE('#0000ff', '#ffffff'); //87.93392126846632
chroma.deltaE('#ffffff', '#0000ff'); //214.6477625497956
```

**Comment by gka** [comment]
that is correct. read more about it [here](https://en.wikipedia.org/wiki/Color_difference#CMC_l:c_.281984.29) and [here](www.brucelindbloom.com/Eqn_DeltaE_CMC.html)

**Comment by kswilster** [comment]
oh, thanks for your time!
