### ISSUE TITLE
Inconsistency in results on RGB/Lab conversions using color.clipped

### ISSUE THREAD

**Issue by Pedrovsky** [gka/chroma.js#146]
Hey, so I was in need of doing some color conversions when I found this pretty cool library. Congrats on that, the library is really useful when working with color.

However, after I tried some simple conversions I found some inconsistent results:
![issue](https://user-images.githubusercontent.com/6876518/29939106-af42bd06-8e82-11e7-8969-f458b4b6621b.png)

So, I'm not sure if is something I don't know about color or if it is something wrong with the library, but the results when converting white, green and blue don't match.

Thanks!

**Comment by gka** [comment]
you're dealing with very slight amounts of clipping here.
note that
```
chroma.lab(99.9, 0,0) // --> #ffffff
chroma.lab(100, 0,0) // --> #ffffff
```
For some reason, JS is not displaying the precision of the numbers in console.log.
But you can test it yourself by comparing with 255:

```js
c = chroma.lab(100,0,0); // #ffffff
c._rgb._unclipped; // [255,255,255,1]
c._rgb._unclipped[0] > 255.000;  // true
c._rgb._unclipped[0] > 255.001;  // false
```
![image](https://user-images.githubusercontent.com/617518/29960504-35fbc6e8-8efc-11e7-82cf-01582faf70cf.png)

so what you're pointing out is not an inconsistency, but very consistent.

if you look at the rgb clipping source code, you see where we're comparing against 255:
 https://github.com/gka/chroma.js/blob/master/src/utils.coffee#L32

the only way to "solve" this would be to round the numbers before testing if clipping occurred.
