### ISSUE TITLE
rgb2hsl returns H: NaN for grays

### ISSUE THREAD

**Issue by mattsoave** [gka/chroma.js#150]
Hello! I noticed that `rgb2hsl()` returns a hue of NaN for grays (e.g. `[150, 150, 150]`). I believe this is happening because `rgb2hsl()` calculates hue by dividing by `(max - min)`, which is equal to 0 for grays. You should be able to fix it by including an if statement that checks for `(max - min) = 0` and setting `h = 0` if so, and continuing your existing hue calculation if not.

**Comment by gka** [comment]
no, the function is returning NaN intentionally. hue = 0 means it's a red tone, which a true gray is not. it might as well be hue =60 or any other value. so I'd rather state that there is no hue than picking just a random color (which happens to be 0 for pure luck).

this also important when interpolating between two hsx colors, where you want to avoid changing the hue when mixing a color with "hueless" gray.

if you want to cast NaN to 0 you will have to do it inside your application.

I don't remember why i went with `NaN`, i could've used `undefined` or `null` as well.  but usinf zero (=red) would be misleading.

-------- Original message --------
