### ISSUE TITLE
1.3.4 released?

### ISSUE THREAD

**Issue by smsaladi** [gka/chroma.js#153]
cdnjs claims to serve chroma.js version 1.3.4 (see [here](https://cdnjs.com/libraries/chroma-js), but I don't see a corresponding tagged release on github. Could you clarify please?

**Comment by gka** [comment]
sorry I just forgot to add the release on github. somehow doing `npm patch version` and `npm publish` is enough to have the package updated on npm, but github still makes me manually "draft a new release", which is really just a thing I need to do for github at this point.

I added one for 1.3.5.
