### ISSUE TITLE
Add linear RGB interpolation

### ISSUE THREAD

**Issue by flying-sheep** [gka/chroma.js#154]
Your RGB interpolation is in the logarithmic sRGB space, which doesn’t match human vision, please check out [this video](https://www.youtube.com/watch?v=LKnqECcg6Gw)

You should add a linear RGB interpolation as demonstrated in [this pen](https://codepen.io/flying-sheep/pen/wPmKmB).

The video should convince you that linear RGB should be the default interpolation mode

**Comment by gka** [comment]
interesting. will take a look.

**Comment by gka** [comment]
added in 1.3.5
https://github.com/gka/chroma.js/blob/master/src/interpolator/interpolate-lrgb.coffee

**Comment by gka** [comment]
oh

**Comment by flying-sheep** [comment]
thank you very much for adding it!

about making it default:

1. if you follow semver, this would simply be a major version bump, just like [matplotlib](http://matplotlib.org/) recently released 2.0 because they updated their defaults.
2. what you added as lrgb is (i think) gamma 1.0. more generically, we could also blend using a custom gamma. d3 color interpolation allows for that.

you should also read this, it’s amazing: http://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

**Comment by gka** [comment]
you're right, a generic gamma manipulator would be a nice addition to `chroma.scale` in general.

**Comment by gka** [comment]
fyi, I added `scale.gamma` http://gka.github.io/chroma.js/#scale-gamma

**Comment by flying-sheep** [comment]
awesome, thank you!

**Comment by gka** [comment]
fyi, `lrgb` is now the default for `chroma.mix` and `chroma.average`.

**Comment by flying-sheep** [comment]
Oh, one question: What’s the reason that it’s not the default in chroma.scale?

**Comment by gka** [comment]
uh, not really sure. will think about it and maybe change it in the next major release.

**Comment by KillyMXI** [comment]
It bugs me that, while `luminance` uses the function defined in sRGB standard (close to gamma 2.2), the `lrgb` interpolation, the way it was implemented, uses some arbitrary value.

The video uses the value of 2 for simplification. It also makes a note that the real value is different.

Here is the illustration:
![](https://i.imgur.com/H6P4obO.png)

And it would be nice if mixing/interpolation and scales were consistent with each other feature-wise, or actually be the same thing.

**Comment by OrderFromChaos** [comment]
This difference between mixing color blending and `.scale` really confused me. I was working on trying to get parity between a chromajs colormap (created with `.scale`) and matplotlib colormap. Matplotlib only has a linear interpolation between colors by default, otherwise you have to homespin your own interpolation.
https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html#matplotlib.colors.LinearSegmentedColormap
