### ISSUE TITLE
Is it possible to create a rainbow scale?

### ISSUE THREAD

**Issue by fcostarodrigo** [gka/chroma.js#155]
I am using the following code to create a rainbow scale:

    const segments = 10;
    const colors = [...Array(360 / segments + 1)].map((d, i) =>
      chroma.hsl([i * segments, 1, 0.5]),
    );

    this.scale = chroma
      .scale(colors);

Is there a better way? Or is this type of scale out of scope?

**Comment by gka** [comment]
It's definitely out of scope for many reasons, but it's still easy to produce ;-)

```js
chroma.scale(['#f00','#0f0','#00f','#f00']).mode('hsl');
```
(please don't ever use it)

**Comment by gka** [comment]
you might want to check out the [cubehelix](http://gka.github.io/chroma.js/#cubehelix) color scale which tries to combine some of the appeal of rainbow scales with a lightness/saturation gradient, so one can actually perceive absolute values.
