### ISSUE TITLE
Clarify what the lightness correction does

### ISSUE THREAD

**Issue by petulla** [gka/chroma.js#157]
Gregor,

Could you help me better understand what [the lightness correction here does](https://github.com/gka/chroma.js/blob/5e9dd8fc2650b0f364d05929fe7e8ad143f44e25/src/scale.coffee#L179-L207)? I understand that it makes the lightness sequentially uniform in Lab space but I'm confused as to how the new color values are chosen from the input values.

I plan to dive into the code but am hoping you could offer an intuition I can match to the code. Thanks.

**Comment by gka** [comment]
I explained it a little bit in the blog post where i was introducing the feature, thought I linked to it from the documentation 

https://vis4.net/blog/2013/09/mastering-multi-hued-color-scales/#auto-correcting-the-lightness
