### ISSUE TITLE
cdnj CDN link is 404

### ISSUE THREAD

**Issue by rgdonohue** [gka/chroma.js#161]
The 1.3.5 version works, but not so for 1.3.6.

[https://cdnjs.cloudflare.com/ajax/libs/chroma-js/1.3.6/chroma.min.js](https://cdnjs.cloudflare.com/ajax/libs/chroma-js/1.3.6/chroma.min.js)

![image](https://user-images.githubusercontent.com/1952205/35413267-1bfdec8c-01dc-11e8-9bdf-ab43e5440289.png)

**Comment by gka** [comment]
it just takes them a few days until the CDN is updated from NPM. I just checked and the file is there
