### ISSUE TITLE
Mixing alpha colors yields some funky results.

### ISSUE THREAD

**Issue by larsenwork** [gka/chroma.js#162]
Mixing black with a transparent color:
```js
chroma.mix('hsla(0,0%,0%,1)', 'hsla(0,100%,50%,0)').css('hsl')
// Returns "hsla(0,100%,25%,0.5)"
// Expected "hsla(0,0%,0%,0.5)"
```

Mixing a color with a semitransparent color
```js
chroma.mix('hsla(0,100%,50%,1)', 'hsla(180,50%,50%,0.5)').css('hsl');
// Returns "hsla(0,25.1%,50%,0.75)"
// Expected "hsla(90,75%,50%,0.5)"
```

**Comment by gka** [comment]
Well, not sure I agree here.

The result is exactly what I expect. In the first example you're mixing opaque black with a transparent red, and the result is a half-transparent dark red.

In the second example it seems that you are expecting the interpolation `mode` to be HSL, when in fact the default mode is RGB.

You can mix colors in HSL space by passing the mode as fourth parameter:
```js
chroma.mix('hsla(0,100%,50%,1)', 'hsla(180,50%,50%,0.5)', 0.5, 'hsl').css('hsl');
// returns "hsla(89.84,74.9%,50%,0.75)"
```
Not sure how you expect 50% opacity as a result of mixing a 100% and 50% opacity. I think the expected "mix" opacity  should be 75%.

**Comment by larsenwork** [comment]
Thanks for the quick reply 😊.

Regarding the opacity. That was a typo. Should be 75% as you wrote.

With regards to the rest I probably got the numbers wrong but I just noticed how it was different from how I'm used to a browser mixing colors when drawing linear gradients:

Browser:
<img width="315" alt="browser" src="https://user-images.githubusercontent.com/3859425/35475284-e2a00ba2-039b-11e8-8b56-0fc150d6a27d.png">

Chroma (with maybe 10 calculated intermediary color stops):
<img width="316" alt="chroma" src="https://user-images.githubusercontent.com/3859425/35475285-e2b6a4ca-039b-11e8-892d-64d39d821f4a.png">

And with the `black` to `hsla(0, 100%, 50%, 0.05)`

Browser:
<img width="307" alt="screen shot 2" src="https://user-images.githubusercontent.com/3859425/35475324-9528455a-039c-11e8-9b5d-495f83430880.png">

Chroma: 
<img width="307" alt="screen shot 1" src="https://user-images.githubusercontent.com/3859425/35475327-9dfaf9f2-039c-11e8-9b7a-5119f772fa4c.png">

**Comment by gka** [comment]
seems the browser is already using linear RGB interpolation by default. we're going to make this the default in chroma.js soon

**Comment by larsenwork** [comment]
Cheers, 

`lrgb` is closer to what the browser produces when mixing two opaque colors: 

Chroma(rgb) | Browser(Chrome ) | Chroma(lrgb)
--- | --- | ---
<img width="316" alt="chroma" src="https://user-images.githubusercontent.com/3859425/35475285-e2b6a4ca-039b-11e8-892d-64d39d821f4a.png"> | <img width="315" alt="browser" src="https://user-images.githubusercontent.com/3859425/35475284-e2a00ba2-039b-11e8-8b56-0fc150d6a27d.png"> | <img width="318" alt="lrgb" src="https://user-images.githubusercontent.com/3859425/35475878-66ec01ea-03a6-11e8-8f6e-da6c4dcccac6.png">

But when mixing `black` and `hsla(0, 100%, 50%, 0.05)` the browsers factors in opacity differently:

Chroma(rgb) | Browser(Chrome ) | Chroma(lrgb)
--- | --- | ---
<img width="307" alt="screen shot 1" src="https://user-images.githubusercontent.com/3859425/35475327-9dfaf9f2-039c-11e8-9b7a-5119f772fa4c.png"> | <img width="307" alt="screen shot 2" src="https://user-images.githubusercontent.com/3859425/35475324-9528455a-039c-11e8-9b5d-495f83430880.png"> | <img width="313" alt="screen shot 3" src="https://user-images.githubusercontent.com/3859425/35475918-271d66ac-03a7-11e8-9513-1cdffe3ba450.png">

**Comment by larsenwork** [comment]
Closing this as it seems browsers can even agree on how to do things. 
Should they a some point do it'd be nice to have a "browser interpolation" mode.
