### ISSUE TITLE
Weird average in LCH (X+X)/2 != X

### ISSUE THREAD

**Issue by 015988** [gka/chroma.js#163]
Is it reasonable that:

`console.log('TEST',chroma.average(["#02c03a", "#02c03a"],'lch').hex());`

prints:
`TEST #00c7f5`

I know that LCH isn't RGB, but I do find it weird that the average of the same colour twice is another colour.... Weird conversion artefact?

**Comment by thorn0** [comment]
Same with HSL:
```js
chroma.average(["#02c03a", "#02c03a"],'hsl').hex()
// #026cc0
```
Meanwhile, `mix` works fine:
```js
chroma.mix("#02c03a", "#02c03a", 0.5, 'lch').hex()
// #02c03a
```
