### ISSUE TITLE
Check for valid color

### ISSUE THREAD

**Issue by ockam** [gka/chroma.js#166]
How can I can check if `chroma()` returns a valid color or an error?

In my app, colors are inputed textually by the user and I need to be able to recover from invalid colors, but I’m unable to figure out what is returned from Chroma.

**Comment by ockam** [comment]
Just occurred to me that I could simply try/catch.

Would still be a nice feature to be able to know if a value is a valid Color.

**Comment by gka** [comment]
yea, I've been using the try/catch way until now.
