### ISSUE TITLE
Luminance method still mutates original Chroma object.

### ISSUE THREAD

**Issue by phyllisstein** [gka/chroma.js#167]
Hey there! I noticed in #100 there was a comment indicating that Chroma functions should no longer mutate the original object, instead returning a new Chroma instance in all cases. I wanted to flag that this is not true of the `luminance` method. A hot five seconds in the REPL confirms:

```
> const chroma = require('chroma-js')
> const original = chroma('white')
> original
Color { _rgb: [ 255, 255, 255, 1, _clipped: false ] }
> const gray = original.luminance(0.5).css()
> gray
'rgb(188,188,188)'
> original
Color { _rgb: [ 188, 188, 188, 1 ] }
```

I don't think I'll have the chance to familiarize myself with the code base and get a PR in for it this weekend, but if you find any time on your end to look into it I'd be grateful. Thanks for all your work on this module!

**Comment by gka** [comment]
this is fixed now, just tested it again
