### ISSUE TITLE
Document random colour distribution

### ISSUE THREAD

**Issue by pnorman** [gka/chroma.js#169]
Picking random colours is actually a hard topic. If you pick random XYZ colours, you'll tend to get a lot more greens than Lab.

The documentation should state what the domain of `chroma.random()` is and what distribution it is within that domain.

**Comment by gka** [comment]
Good point! 

The chroma.random is generating a random hexadecimal string. 
https://github.com/gka/chroma.js/blob/master/src/generator/random.coffee#L3-L7

Not sure if that is a particularly smart way to compute random colors or not (happy to add a better one). I will make this more clear in the documentation though.
