### ISSUE TITLE
Standardize BSD3 license

### ISSUE THREAD

**Issue by alex-deas** [gka/chroma.js#170]
The license appears to BSD3 however the `LICENSE` file includes the phrase "All rights reserved", this phrase contradicts the spirit of the BSD license and causes issues for licensing software to recognise the license file.

Could we update the LICENSE file to use the standard BSD3 License?
https://opensource.org/licenses/BSD-3-Clause

**Comment by gka** [comment]
not sure when this was changed but clearly, the "all rights reserved" at some point was part of the standard licence. The wikipedia page on the BSD license still has the phrase in each version: https://en.wikipedia.org/wiki/BSD_licenses

**Comment by alex-deas** [comment]
It's a bit of a strange one because the BSD license doesn't include it and afaik never has. A lot of license generation tools seem to just be including it as part of the text
