### ISSUE TITLE
Unable to implement variables.

### ISSUE THREAD

**Issue by Ash110** [gka/chroma.js#173]
After linking the chroma.js to my index.html, I proceeded with these lines in my js file - 
    ```var c0 = "#f3de7c";
    var c1 = chroma(c0).hex(); ```

However, it's not working. Any help?

**Comment by henrikhelmers** [comment]
This is more of a support request than an issue with chroma.js. What does the console say?

**Comment by gka** [comment]
yep, not sure what's the problem here, but I suggest you just google for the error message and will probably find help on stackoverflow.
