### ISSUE TITLE
chroma.deltaE is not really Delta E

### ISSUE THREAD

**Issue by jiho** [gka/chroma.js#175]
Hi,
First, thanks for the great lib!

The structure of the [wiki page on Delta E](https://en.wikipedia.org/wiki/Color_difference#CIELAB_Delta_E*) is not very clear but it still states that Delta E was defined by the CIE. There are various versions of the metric (76, 94, 2000), each coming with additional corrections.

The implementation of Delta E in chroma.js is that of [CMC l:c](https://en.wikipedia.org/wiki/Color_difference#CMC_l:c_(1984)) which was defined by the "Colour Measurement Committee of the Society of Dyers and Colourists", *not* the CIE. So, even though it is defined as a subsection of the Delta E section on wikipedia, does not seem to be a Delta E metric (and the non commutability of the arguments is a tell of that).

@Offirmo proposed an implementation of Delta E 94 in #127. I implemented Delta E 2000 [there](https://github.com/jiho/chroma/blob/master/R/compute_deltaE.R) (see the `deltaE_lab` function), albeit in R, but it should not be very hard to convert to js. It is checked against the data in the paper by Sharma et al 2005 and is correct.

I would suggest using one of those as chroma.deltaE and redefining the current deltaE as chroma.CMClc.

Thanks in advance!

**Comment by danburzo** [comment]
They are all different formulas for computing ΔE (difference in sensation). CMC is a first development (1984) of the CIE76 formula, followed by CIE94 in 1994 and CIEDE2000 in 2000.  Although the Wikipedia page doesn't list them chronologically, you can see in the formulas a natural progression when computing ΔE from a simple Euclidean distance, to different, and more sophisticated ways of weighting the different components of the CIELab color space.

**Comment by gka** [comment]
I think if I remember correctly I picked the CMClc because the simple Euclidean Lab distance can already be computed using [chroma.distance(color1, color2, 'lab')](http://gka.github.io/chroma.js/#chroma-distance). I think Lab is even the default color space, so you can just call `chroma.distance`. 

Having said that I would be happy to use the deltaE 2000 as new default "deltaE" if that is more useful. I can look into the reference implementation in R.

**Comment by jiho** [comment]
Thanks for the precision. Indeed, the formulas are close. @gka, if you feel lazy, the 94 implementation, in js, at #127 would probably be better already (commutative at least).

**Comment by danburzo** [comment]
If it helps in any way, I've implemented the differences [here](https://github.com/danburzo/d3-color-difference) as a d3 module. [This Observable notebook](https://beta.observablehq.com/@danburzo/color-difference-formulas-with-d3-color-difference) shows how they stack up.

**Comment by gka** [comment]
haha, wow there's so many of them!  :)

so which one is "the best"? CIE2000?

**Comment by danburzo** [comment]
Yes, CIEDE2000 is the one widely used, and is symmetrical.

PS: CIE94 — as presented on the Wikipedia page, implemented in d3-color-difference, and in https://github.com/gka/chroma.js/issues/127 — is _not_ symmetrical, since it relies on a _standard_ color vs. a _sample_ color. (Although it can be _made_ symmetrical)

**Comment by trenaryja** [comment]
Hello @gka! I wanted to see if there were any plans to update the deltaE function with the CIEDE2000 formula mentioned by @jiho and @danburzo? Here is a link to a library that has implemented many of the deltaE functions in javascript already:  [link](https://github.com/zschuessler/DeltaE)

I hope that this is useful! Thanks for the hard work and great lib!

**Comment by henrikhelmers** [comment]
I was also curious as to which version. I think it'd be good to add a comment that it is currently using the '94 version.

**Comment by vasilzhigilei** [comment]
Agreed with the other users in the thread, CIE2000 would be perfect!

**Comment by vasilzhigilei** [comment]
Hi, I've fixed the issue in this thread @gka, it can be closed after PR merge.

**Comment by michel-leonard** [comment]
The implementation of ΔE2000 in now available in 26 versions at [github.com/michel-leonard/ciede2000-color-matching](https://github.com/michel-leonard/ciede2000-color-matching). The source code is in the public domain, and fully tested.
