### ISSUE TITLE
Support for alpha channel in .hex()

### ISSUE THREAD

**Issue by maxaggedon** [gka/chroma.js#177]
I have noted that
```
chroma('white').alpha(0.1).hex()
```
returns `"#ffffff"` whereas I expected it to return `"#ffffff19"`.

I don't know if it's intentional but I guess I'm not the only one to expect hexadecimal representation to include the alpha channel.

**UPDATE**
By looking into the code, I realised the following works:
```
chroma('white').alpha(0.1).hex('rgba')
```
It would be great to document that, or even better to automatically switch mode if alpha is present.

**Comment by gka** [comment]
I agree that automatically setting the mode to `rgba` would make sense, but this is also potentially breaking some apps that are using chroma. still inclined to add this to the next version.

**Comment by gka** [comment]
this is included in chroma.js version 1.4.0 
* changelog: https://github.com/gka/chroma.js/blob/master/CHANGELOG.md#140
* docs: https://gka.github.io/chroma.js/#color-hex
