### ISSUE TITLE
Check if color is dark or light?

### ISSUE THREAD

**Issue by raRaRa** [gka/chroma.js#181]
`TinyColor` and other color libraries have something like `color.isDark()` which returns true if the color is dark. The isDark method seems to be checking the brightness of the color:

```
isDark: function() {
    return this.getBrightness() < 128;
}

getBrightness: function() {
    //http://www.w3.org/TR/AERT#color-contrast
    var rgb = this.toRgb();
    return (rgb.r * 299 + rgb.g * 587 + rgb.b * 114) / 1000;
}
```

Is there something equivalent in chroma? There seems to be `color.luminance`, but would that be adequate to check if a color is dark?

Thanks.

**Comment by imkremen** [comment]
@raRaRa Yes, use `color.luminance` ([defenition](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef))

You can also check `chroma.contrast`, it useful if you need to check contrast between background and foreground. [(defenition)](https://www.w3.org/TR/WCAG21/#contrast-minimum)
