### ISSUE TITLE
Easy way to create color scale legend bar?

### ISSUE THREAD

**Issue by tylorbayer** [gka/chroma.js#186]
Is there an easy way to create the color scale legend bars with the values used like you have on the api docs?

<img width="173" alt="screen shot 2018-07-16 at 2 39 59 pm" src="https://user-images.githubusercontent.com/25021603/42782444-343d5ede-8906-11e8-9dd1-d56b000a08ab.png">

**Comment by gka** [comment]
I'm afraid this is out of scope for chroma-js, but feel free to steal the code and CSS from the docs https://github.com/gka/chroma.js/blob/master/docs/src/footer.inc.html#L70-L80
