### ISSUE TITLE
SRGB -> RGB cutoff divergence

### ISSUE THREAD

**Issue by hibikir** [gka/chroma.js#189]
the SRGB to RGB conversion step in the LAB -> RGB transformation step is a bit off from the spec:

http://www.color.org/srgb.pdf

This is a known issue from copying the draft W3C specification instead, which has a slightly wrong number: It should be 0.031308 instead of what the old draft says, 0.03928. If you go to the W3C draft, it warns that it's obsolete, and to go look at the updated IEC 61966-2-1 SPEC.

I can write a PR if you like, but it's such a simple change that, if you do the legwork and read the updated spec, chances are you'd rather do it yourself.

**Comment by thorn0** [comment]
Where did you find 0.03928 in the code? It seems to be used only in the `luminance_x` function, which is not part of the LAB -> RGB transformation.

**Comment by gka** [comment]
..and the 0.03928 is still referenced in the W3C specs of luminance: https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef

@hibikir can you perhaps be more specific on what you think needs to be changed?

**Comment by gka** [comment]
closing this for now... feel free to re-open
