### ISSUE TITLE
Add docs for chroma('red').num() and other undocumented functions (Convert color to 0xRRGGBB format (instead of only #RRGGBB))

### ISSUE THREAD

**Issue by hackhat** [gka/chroma.js#190]

**Comment by davidfig** [comment]
It's not documented but you can call chroma('red').num() and it converts to 0xrrggbb format

**Comment by gka** [comment]
makes sense. added a section here https://gka.github.io/chroma.js/#color-num

**Comment by hackhat** [comment]
thanks. Look for other undocumented features if any.
