### ISSUE TITLE
Some colour sets result in greyscale gradient when Bezier interpolation is toggled

### ISSUE THREAD

**Issue by kazerniel** [gka/chroma.js#191]
I just wanted do find equidistant colours within that range :)

Screenshots: https://imgur.com/a/XZc9tSt

**Comment by gka** [comment]
the input colors need to already be either only increasing or decreasing in lightness from left to right. in this case the orange at the end is darker than the yellow. if you're aiming for a diverging color scheme with yellow in the center, try using the diverging mode
