### ISSUE TITLE
ThreeJS compatible color formatting

### ISSUE THREAD

**Issue by z3to** [gka/chroma.js#193]
As Threejs (and maybe other WebGL frameworks) [recommends](https://threejs.org/docs/#api/en/math/Color) hexadecimal triplet color formatting in a different (don’t know the name) format (i.e. `0xff0000`) it would be great if ChomaJS would support that natively.

Currently, I need to convert the hex output:
```js
parseInt('0x' + color.hex().substr(1), 16)
```

**Comment by gka** [comment]
That's what [color.num()](https://gka.github.io/chroma.js/#color-num) is for :)

```js
chroma('red').num() == 0xff0000
```
