### ISSUE TITLE
color validation

### ISSUE THREAD

**Issue by damiweb** [gka/chroma.js#195]
Hey, 
That library is really nice, and have a lot of useful functions, but you forget about one, the most important method - validate(). It is confusing, when library can interpret so much color formats, but I have to write my own function to validate that color have correct format, before passing it to constructor. The only option right now is to wrap construct function with try-catch, but it is not elegant solution.

**Comment by Kikketer** [comment]
It also seems a bit too lax at times for example sending in this:
```
chroma('linear-gradient(to right, rgba(255,255,255,1) 0%,rgba(232,232,232,0.6) 100%)').css()
```
returns
```
`rgb(255,255,255)`
```

While
```
chroma('shinanigans')
```
throws the exception.

**Comment by gka** [comment]
yes, good points. I will add `chroma.isValid(color)` in the next release!

**Comment by gka** [comment]
added in 2.0.1 https://vis4.net/chromajs/#chroma-valid (as `chroma.valid`)
