### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by Ambyjkl** [gka/chroma.js#197]
13.4 kB gzipped is by no means "tiny", like the README suggests: https://bundlephobia.com/result?p=chroma-js@1.4.0. If only using certain features, one should be able to load them individually.

Rather than just concatenating source files together, we need to use proper imports/exports and translate each .coffee file into a corresponding .js file into a `lib` folder.

**Comment by gka** [comment]
I started this at some point last year but didn't have the time and energy to go through https://github.com/gka/chroma.js/tree/es6

would you be up to help with this?

**Comment by Ambyjkl** [comment]
Sure, I'll try and do something when I get the time

**Comment by alekmych** [comment]
May I suggest a TypeScript rewrite?

**Comment by gka** [comment]
alright I started another run for the es6 rewrite, this time in [es6-rewrite](https://github.com/gka/chroma.js/tree/es6-rewrite).

started to go through the source tree from top to bottom. will make jumps to files that are required when needed (like the utils). also will add new unit tests along the way (the new tests are in `test/unit` for now).

the old coffee sources will remain in the branch for now, as a reference until the whole rewrite is done.

**at this point I will not make a lot of changes to the code structure**. I just want to get this rewrite over with as fast as possible. more refactoring can be done later if needed.

I have never used TypeScript and I won't start to learn it now for this project.

**Comment by gka** [comment]
done!

**Comment by stevenadams** [comment]
@gka sorry I know this is a really old issue, but I was wondering if you could update the docs at some point to show examples of how to import only the part of chroma you are using. For example, I am only using the `.get()` functionality. How would I go about only importing this vs `import chroma from 'chroma-js'`. Sorry if this is a really novice question but I've been trying a few things and can't work it out.
