### ISSUE TITLE
Feature Request: Google Apps Script Support

### ISSUE THREAD

**Issue by leoherzog** [gka/chroma.js#207]
Amazing library, thanks for all your work.

It would be great if Chroma worked out-of-the-box with [Google Apps Script](https://developers.google.com/apps-script/).

If I:
1. Copy and paste [the latest `chroma.js` release](https://raw.githubusercontent.com/gka/chroma.js/v2.0.2/chroma.js) into a script file in an apps script project
2. Write a function like `function test() { chroma('red'); }`
3. Run the function

I get the error `TypeError: Cannot convert null to an object. (line 198, file "chroma")`. It points me to the line
`198:      return new (Function.prototype.bind.apply( chroma.Color, [ null ].concat( args) ));`
in Chroma.js.

**Comment by leoherzog** [comment]
Apps Script uses ES3 with a few cherrypicked ES5 features. `chroma().contrast` works if I include [an `Array.includes()` polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill) in the project, but `chroma('color')` still doesn't work. I assume the problem is some other modern-ish function that Chroma is using that isn't supported in Apps Script? I've tried running it through Babel first, but no luck.

**Comment by gka** [comment]
At the moment I have no plan of supporting EcmaScript 3 (which came out 20 years ago!). Sorry if that means you can't use chroma.js in Google App scripts.

**Comment by Artoria2e5** [comment]
This is really Google's fault, and.. Google does have a "Closure Compiler" thingy that transcompiles to ES3.

**Comment by leoherzog** [comment]
Now that [Google Apps Script supports the V8 runtime](https://developers.google.com/apps-script/guides/v8-runtime) with modern Javascript features, I'm happy to report that Chroma.js works perfectly.
