### ISSUE TITLE
darken/brighten compared to SASS

### ISSUE THREAD

**Issue by alamothe** [gka/chroma.js#217]
Hello,
I'm wondering about the relationship (if any) of `darken`/`brighten` functions to SASS functions `lighten`/`darken`: https://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method

According to SASS documentation, it looks like it will increase/decrease lightness.

 How about Chroma? 

Chroma's functions take a value parameter - what does it represent?

Context: I'm trying to replicate SASS behavior in JS.

Thanks!

**Comment by jaredklewis** [comment]
The SASS darken and lighten functions adjust the HSL lightness of the color. The chroma-js darken and lighten functions appear to adjust the CIEL\*a\*b lightness of the color.

You can still adjust the HSL lightness though:

```js
const chroma = require("chroma-js");

// HSL manipulators
const lighten = (color, hslPercent) => color.set("hsl.l", color.get("hsl.l") + hslPercent);
const darken = (color, hslPercent) => lighten(color, -hslPercent);

// equivalent to SASS lighten(#ff0000, 10%)
lighten(chroma("#ff0000"), 0.1).hex(); // => '#ff3333'

// equivalent to SASS darken(#ff0000, 10%)
darken(chroma("#ff0000"), 0.1).hex();  // => '#cc0000'
```

SASS example: https://jsfiddle.net/1tbxvzyo/

**Comment by alamothe** [comment]
@jaredklewis Thanks for the code! I think in your example the parameter should actually be `10` instead of `0.1` if you want to do 10% (or you need to multiply by `100` inside the function, whichever is your convention).

You might be right about color space difference - I have no idea how to tell. 

Another difference is that Chroma's `darken/brighten` multiply value with a constant defined here:  https://github.com/gka/chroma.js/blob/master/src/io/lab/lab-constants.js#L4

While SASS simply takes a value between 0 and 100. I have no idea what Chroma's constant represent.

**Comment by jaredklewis** [comment]
>  I think in your example the parameter should actually be 10 instead of 0.1 if you want to do 10% (or you need to multiply by 100 inside the function, whichever is your convention).

No, chroma-js HSL values are between 0 and 1, not 0 and 100.

```js
chroma("#ff0000").get("hsl.l"); // #=> 0.5
```

You can also try the code from my last comment and verify for yourself that it works the same as SASS.

**Comment by alamothe** [comment]
All makes sense now, thanks!
