### ISSUE TITLE
how convert hex to hsla ?

### ISSUE THREAD

**Issue by ivan-vilches** [gka/chroma.js#226]
There is a method for convert hex to hsla? thanks

**Comment by gka** [comment]
yes it does:
```js
chroma.hsl(330, 1, 0.6).alpha(0.5).hex()
// or
chroma("hsla(180,50%,30%,0.5)").hex();
```

**Comment by vtmx** [comment]
Hex to hsla not hsla to hex.

**Comment by vtmx** [comment]
> yes it does:
> 
> ```js
> chroma.hsl(330, 1, 0.6).alpha(0.5).hex();
> // or
> chroma("hsla(180,50%,30%,0.5)").hex();
> ```
Hex to hsla not hsla to hex.
