### ISSUE TITLE
Feature Request: Auto Legend

### ISSUE THREAD

**Issue by SumNeuron** [gka/chroma.js#227]
I have done a lot of d3 inside and out. chroma is nice for when I just need to color some html elements. Still would like to have a legend. Would be nice if I could just call

chroma.legendify(scale, element), and it produces a flexible legend in that element

**Comment by meodai** [comment]
What would the output of legendify be? An array of color names?

**Comment by SumNeuron** [comment]
more like div.gradient from https://vis4.net/chromajs/
like the actual color scale.

**Comment by meodai** [comment]
can you show an example input and example output that goes with it?

**Comment by SumNeuron** [comment]
Something like

```
scale = chroma.scale(...)//... .domain(...) etc

opts = {...} // continuous: true / false, orient: horizontal, ...

legendify(scale, opts, '#legend-container')
```
<img width="278" alt="Screen Shot 2019-09-09 at 6 33 24 AM" src="https://user-images.githubusercontent.com/22868585/64503589-fdd06d80-d2cb-11e9-8f8d-3bc84efbb61a.png">

or 



<img width="171" alt="Screen Shot 2019-09-09 at 6 35 43 AM" src="https://user-images.githubusercontent.com/22868585/64503657-396b3780-d2cc-11e9-848a-518337e9caab.png">

**Comment by meodai** [comment]
As chroma is a utility library to work with colors, I don't think it should produce anything DOM related. Also doing this is a 3 liner or something: https://codepen.io/meodai/pen/25212ed1350238aca28d4e9535cf87e3

**Comment by meodai** [comment]
@gka I think this can be closed

**Comment by boeckMt** [comment]
A colleague of mine created [dv-scalebar](https://github.com/indus/dv-scalebar) maybe it can be helpful for some one.
