### ISSUE TITLE
Add support for WCAG 3 contrast check with APCA

### ISSUE THREAD

**Issue by mkalamarz** [gka/chroma.js#302]
Currently, [chroma.contrast()](https://vis4.net/chromajs/#chroma-contrast) caters only to WCAG 2 standard. But it sometimes behaves unexpectedly.

![image](https://user-images.githubusercontent.com/28183554/186008222-671d9482-0b8a-420f-bb5b-3105bc9b041a.png)

Would you consider adding APCA (Advanced Perceptual Contrast Algorithm) contrast check as parameter to this or as a new function?

**Comment by jshmllr** [comment]
Bump

**Comment by HM100** [comment]
Bump

**Comment by gka** [comment]
yes, we'll add this in the next release

**Comment by insilications** [comment]
Thanks for adding this feature. It will help a lot.
