### ISSUE TITLE
Color scale look up table?

### ISSUE THREAD

**Issue by nikkopante** [gka/chroma.js#314]
In chroma.js, there are named color palletes or 'scales' such as Viridis, Spectral, RdYlBu (Red, Yellow, Blue), Reds, Greys, etc. I know some of these are based on Color Brewer. However, I do not see a complete look up table in the docs for these names with their colors. How can I know that such acronym would work such as "RdYlBu"?

**Comment by zyyv** [comment]
Refer to https://github.com/gka/chroma.js/blob/b1d13bd91b845a98853d173526d5b2c6c0df07ef/src/colors/colorbrewer.js#L20-L59

Sorry for the lack of examples in the documentation, but it will hopefully become more interactive in the new documentation.

**Comment by gka** [comment]
You can access a list of all available palettes via
```js
Object.keys(chroma.brewer)
// ['OrRd', 'PuBu', 'BuPu', 'Oranges', 'BuGn', 'YlOrBr', 'YlGn', 'Reds', 'RdPu', 'Greens', 'YlGnBu', 'Purples', 'GnBu', 'Greys', 'YlOrRd', 'PuRd', 'Blues', 'PuBuGn', 'Viridis', 'Spectral', 'RdYlGn', 'RdBu', 'PiYG', 'PRGn', 'RdYlBu', 'BrBG', 'RdGy', 'PuOr', 'Set2', 'Accent', 'Set1', 'Set3', 'Dark2', 'Paired', 'Pastel2', 'Pastel1']
```

as of now, this list will also include lowercase representations for each palette, but this will be fixed in the next release.
