### ISSUE TITLE
HCL / LCH plain js object not constructing the correct colors.

### ISSUE THREAD

**Issue by asp55** [gka/chroma.js#315]
Constructing a color using `chroma(h, c, l, 'hcl')` format is resulting in a different (correct) value from constructing with plain js object `chroma({h:h, c:c, l:l})`

See screenshot of using following constructors inside documentation page.

```chroma(80, 25, 200, 'lch');
chroma({ l:80, c:25, h:200 });

chroma(200, 25, 80, 'hcl');
chroma({ h:200, c:25, l:80, });
```

<img width="622" alt="DemonstratedInsideDocumentation" src="https://github.com/gka/chroma.js/assets/5753295/eeafa8a5-422c-442c-9d26-a8421a824861">

**Comment by prjctimg** [comment]
I also noticed the same bug. It may be that the constructor is not passing the `mode` parameter internally thus it returns default black. A work around would be passing the `mode` parameter as a property of the destructured color object like so:

```
chroma({ l:80, c:25, h:200,mode:'lch' });

```



Or the code could be internally modified to extract the `mode` from stringifying the objects enumerable properties like so (pseudocode):

```
let color = { l:80, c:25, h:200 }
let mode = color.keys.toString()


```

**Comment by gka** [comment]
this bug seems to have been fixed already. I [added these tests](https://github.com/gka/chroma.js/commit/89c416a3690d9ff1422f9417f163278ae835d662) to our test suite to confirm this:

```js
it('create lch color from object', () => {
    expect(new Color({ l: 80, c: 25, h: 200 }).hex()).toBe('#85d4d5');
    expect(chroma({ l: 80, c: 25, h: 200 }).hex()).toBe('#85d4d5');
    expect(chroma.lch(80, 25, 200).hex()).toBe('#85d4d5');
    expect(chroma(80, 25, 200, 'lch').hex()).toBe('#85d4d5');
});

it('create hcl color from object', () => {
    expect(new Color({ h: 200, c: 25, l: 80 }).hex()).toBe('#85d4d5');
    expect(chroma({ h: 200, c: 25, l: 80 }).hex()).toBe('#85d4d5');
    expect(chroma.hcl(200, 25, 80).hex()).toBe('#85d4d5');
    expect(chroma(200, 25, 80, 'hcl').hex()).toBe('#85d4d5');
});
```

**Comment by prjctimg** [comment]
Thanks again! 💯
