### ISSUE TITLE
Brewer scales does not seem accurate

### ISSUE THREAD

**Issue by yohanboniface** [gka/chroma.js#316]
Hi!

When using this example from the documentation:

```
>> chroma.scale('OrRd').colors(5);
Array(5) [ "#fff7ec", "#fdd49e", "#fc8d59", "#d7301f", "#7f0000" ]
```

I would expect it to return the same colors as [ColorBrewer](https://colorbrewer2.org/#type=sequential&scheme=OrRd&n=5) would do:

![image](https://github.com/gka/chroma.js/assets/146023/02c6c1dc-18b9-4f35-9851-7ff80c448ef9)

But the results differ:

- chroma-js:      `#fff7ec, #fdd49e, #fc8d59, #d7301f, #7f0000`
- ColorBrewer: `#fef0d9, #fdcc8a, #fc8d59, #e34a33, #b30000`

When I look at the chroma-js code handling this, it seems to me that indeed the brewer management is simplified. But I'm not sure at this point if this is a bug or a feature (to keep the code simple). And also I may be missing something.

So if this is considered as a bug, I can try to work on a proposal. If it's a feature, let's close! And if I'm misunderstandin something, sorry for the noise!

**Comment by gka** [comment]
I know that the official brewer scales are hand-picked colors that vary depending on how many colors you want to use in your visualization. In chroma.js we're using the versions with the most colors (e.g. 9 colors for sequential scales) and then interpolating between them.

The idea is to get you close to ColorBrewer while allowing you to switch to any number of "steps" you want. If you want to use exactly the 5-color scale from https://colorbrewer2.org/ you can just copy those colors and use them, and don't need chroma.js at all.

But it's worth adding a note about this to the documentation.
