### ISSUE TITLE
[Question] State of this library?

### ISSUE THREAD

**Issue by nickofthyme** [gka/chroma.js#317]
The last release was [`2.4.0`](https://github.com/gka/chroma.js/releases/tag/v2.4.0) in February of 2022.

I see a lot of issues/bugs and several valid new-contributor pull requests fixing issues with no comments from contributors, long after opening their PR.

~But I don't see anything in the readme about the state of this library being inactive or otherwise.~

Sorry just saw this...question still stands

> There have been no commits in X weeks. Is chroma.js dead?
>
> No! It's just that the author of this library has other things to do than devoting every week of his life to making cosmetic changes to a piece of software that is working just fine as it is, just so that people like you don't feel like it's abandoned and left alone in this world to die. Bugs will be fixed. Some new things will come at some point. Patience.

So my question is what is the current state of this library? Is this library active where opening a PR will be reviewed and released or should people not bother? Asking for a friend 😉 ✌🏼

**Comment by gka** [comment]
Nope, chroma.js is maintained! we just released version 3.0.0. Happy to add more maintainers though, feel free to join our [Discord chat](https://discord.gg/5pB7WgDs) if you want to contribute @trusktr or @nickofthyme.
