### ISSUE TITLE
Add ARGB

### ISSUE THREAD

**Issue by jclarkcisco** [gka/chroma.js#319]
I see `color.hex('argb')` in code, and an older PR for it, but it doesn't seem to be part of the typings or documentation. Maybe this was disabled by accident, but it's needed for anyone needing to output colors for Android.

**Comment by gka** [comment]
good point. we should add it to the documentation, at least. as for the typing, I think there's a big discrepancy between the current chroma.js API and what's on [typed/chroma.js](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chroma-js). Not sure what's the best way to fix this, but we're already thinking about porting chroma.js to TypeScript.
