### ISSUE TITLE
Channels API

### ISSUE THREAD

**Issue by dfcreative** [gka/chroma.js#32]
Is there a way to set/retrieve channel value, as it is done in [harthur/color](https://github.com/harthur/color)? Or are there any plans on that?
E. g.
```js
var Color = requie('chroma');
var c = new Color('gray');
c.red(); //128
```

**Comment by polarathene** [comment]
I've been using harthur/color[https://github.com/harthur/color] and just came across chroma.js. I'd appreciate a channels api too. Chaining the channel call to the color space is fine, though if possible it might be nicer if the color space call returned the chroma instance toggled to that mode for additional chaining.

```javascript
var c = chroma('beige').hsl()
c.hue() //60
c.hue(40) //alters the color hue and returns the instance
c.rgb().r(255).hsl().saturation(0.5).hue() //switch color spaces and chain channels, returns the hue

var c2 = chroma( c.hex().r() ) //returns hex string only containing the red channel and creating a new chroma based on that typed to rgb color space
c2.hsl().rotate(45) //rotates/increases the hue by 45deg
```

Thoughts? Glancing over the api docs I'm assuming that the value given to chroma() is rather clear what color space it belongs to, I haven't looked into how you're handling it internally.

**Comment by gka** [comment]
Internally, every color is stored as RGB in chroma.js, so no, it does not know what color space a color belongs to.  chroma.js reads colors and outputs colors. it doesn't have a nice way to manipulate a single component of a color, mainly because I never use this.

**Comment by gka** [comment]
closing for now.
