### ISSUE TITLE
Feature request: Add a way to retrieve the domain from a color scale

### ISSUE THREAD

**Issue by gewesp** [gka/chroma.js#320]
Maybe I missed it in the docs, but there doesn't seem to be a way of retrieving the domain of a color scale.

More specifically, I'd like:
```
const scale = chroma.scale(['yellow', 'black']).domain([0,100]);
assert(scale.newFunctionToGetMaxDomainValue() === 100);
```
Should be quite simple to add, no?  We can prepare a PR if required.

**Comment by gka** [comment]
you can call `scale.domain()` without arguments to retrieve the current domain:

```js
const scale = chroma.scale('Reds').domain([0,100]);
const [min, max] = scale.domain();
```
