### ISSUE TITLE
Updated fork

### ISSUE THREAD

**Issue by regorxxx** [gka/chroma.js#321]
An updated fork can be [found here](https://github.com/regorxxx/chroma.js), with all dependencies updated, vulnerabilities fixed and new features (along relevant pendant pull request).

https://github.com/regorxxx/chroma.js

Docs have also been updated. Can be replaced directly without changes.

**Comment by trusktr** [comment]
@gka @regorxxx @iyinchao @stormwarning @salvoravida @artoria2e5 @OlaoluwaM @tstaylor7 @tremby @taisukef 

Hello you all! I tagged you because you're either the original owner of this repo, or someone who most-recently made significant features and updates in a fork of this repo (I looked at the network graph).

I figured, so as not to let this project get stale, perhaps we can all get together and help maintain a fork of it.

I started a fork from @regorxxx's in a new org, and I've invited you all to the org (anyone else want to join, please comment here!):

https://github.com/chroma-js/chroma.js

I will taking some inspiration from @taisukef's [fork](https://github.com/code4fukui/chroma-es) and starting from @regorxxx's fork making it all work as vanilla ES Modules, and deleting all traces of CommonJS (we can optionally add a CommonJS build if people really need that, but CommonJS is the past, ES Modules are the present and the future).

**Comment by tremby** [comment]
Thanks for pointing it out. If I reach for Chroma again at some point I'll consider using the fork. But in truth I haven't felt much need for Chroma since browsers improved their colour space support to include things like Oklab and Oklch.

**Comment by tremby** [comment]
Oh I see you invited me to join the org too. I'm not going to at this point; one reason is that I feel a bit uncomfortable about it being named "chroma-js" without signoff (as far as I know) from the original author.

**Comment by taisukef** [comment]
Thank you for pointing it out!
I use ES Modules on browsers and Deno, so I forked and converted CommonJS sources.
https://github.com/code4fukui/chroma-es/tree/es/src
I hope you will make good use of this repository.
Please let us know if there's anything missing or if you have any suggestions.

**Comment by trusktr** [comment]
> Oh I see you invited me to join the org too. I'm not going to at this point; one reason is that I feel a bit uncomfortable about it being named "chroma-js" without signoff (as far as I know) from the original author.

That's easy to change. The original author @gka is also invited.

GitHub does not allow user names or org names with a period, so `github.com/chroma.js` is not allowed, and `github.com/chromajs` and `github.com/chroma` are both already taken by unrelated projects. So `github.com/chroma-js` was the only close-enough option.

**Comment by trusktr** [comment]
I force pushed to https://github.com/chroma-js/chroma.js as there was one small mistake, now the `test/html/*.html` files all work as expected.

**Comment by trusktr** [comment]
Aaaaaaalrighty! An initial working test for Deno is pushed @taisukef.

```js
    "test:deno": "deno run test/test-deno.js",
```

**Comment by trusktr** [comment]
Most tests passing in Chrome browser running as vanilla ES Modules. Need to iron a few out:

```
Chrome: |██████████████████████████████| 50/50 test files | 1956 passed, 69 failed

Finished running tests, watching for file changes...
```

**Comment by trusktr** [comment]
@regorxxx @taisukef there's one particular test where the numbers are quite different between both of your forks. I'm wondering why that is. Here are the tests in question:

https://github.com/chroma-js/chroma.js/blob/340438a65d16e594e587f7fe72b98b0f924294d6/test/bezier.test.js#L133-L238

Both of your forked from this repo's 2.4.2 release, and one fork changed something that modified the numbers and I'm wondering what's correct.

**Comment by regorxxx** [comment]
@trusktr The original repo had wrong values and wrong tests.

I also added proper n-degree bezier interpolation.

All my changes are documented on the changelog ;)

**Comment by regorxxx** [comment]
Once I have time, if I find working with ES modules is easier for me, I will help with that. 

Right now I'm using chroma within a context where modules are not available and only just plain JS loading of files or require. If I can not work around that, will continue developing my fork.

**Comment by trusktr** [comment]
> The original repo had wrong values and wrong tests.
> Also see this: #228
> documented on the changelog ;)

@regorxxx ah, thanks!

>  if I find working with ES modules is easier for me, I will help with that.

I hope you will! 

ESM is the future-forward module standard for all JS runtimes, so we should support it as a default anyway.

We can add CommonJS or global build back fairly easily, but:

> context where modules are not available and only just plain JS loading of files or require

Out of curiousity, what context is that and how does it stop you from using ESM? Is it an old browser or Node version? All browser and non-browser JS runtimes today support `import(...)` in any script (module or not).

**Comment by regorxxx** [comment]
@trusktr Not a browser related context, but [foobar2000](https://www.foobar2000.org/). There are JS plugins for it, so I can use most libraries with full support for ES6. But import/require, etc. are not available. I can polyfill require, but can not do that with import.

**Comment by regorxxx** [comment]
Added a few more features on 2.7.0, along a fix to the 'npm run docs-preview' command which was not working on some OSes.

Also a logo for the library
https://regorxxx.github.io/chroma.js/
![image](https://github.com/gka/chroma.js/assets/83307074/67012977-ff3a-43f4-85cf-068460f95b2d)

**Comment by itsjavi** [comment]
Thanks for the effort in this fork,
how am I supposed to installed it via npm/pnpm?

I keep getting the old 2.4.2 version. Are the instructions [on the website](https://regorxxx.github.io/chroma.js/) up to date?

**Comment by regorxxx** [comment]
Obviously forks are not on npm. Download from github

**Comment by gka** [comment]
whoops, sorry for not noticing this. happy to move chroma.js to a different repo if more ppl feel inclined to help. however, I'm in the middle of a big refactoring so we may want to wait for this before moving the repo (see #336)

**Comment by gka** [comment]
Also, very open to a general discussion about the future of chroma and opening the project to more maintainers since I'm pretty busy most of the time. How about we try to set up a call or a Discord group, perhaps this one https://discord.gg/m2M7k5Nf ? Looking forward to collaborating!
