### ISSUE TITLE
Got hue value `NaN` from chroma('#000000').oklch()

### ISSUE THREAD

**Issue by hallee9000** [gka/chroma.js#322]
![image](https://github.com/gka/chroma.js/assets/12868055/b9fdfd0f-5ead-404c-8ebf-f430d55bc8e9)

**Comment by regorxxx** [comment]
See this https://github.com/gka/chroma.js/issues/321
Read the docs, it's intended that colors with no hue should return NaN.

On the updated repo there is a way to change this behavior.

**Comment by gka** [comment]
as explained by @regorxxx , this is the intended behavior and it's explained in the documentation
