### ISSUE TITLE
OKLCH support in `css()` 

### ISSUE THREAD

**Issue by oskarkrawczyk** [gka/chroma.js#325]
Right now the `css()` method only supports two modes of generating a CSS string, `rgb` and `hsl` – would it be possible to provide additional types, like `oklch`?

**Comment by regorxxx** [comment]
See this https://github.com/gka/chroma.js/issues/321

**Comment by regorxxx** [comment]
I'm just pointing you to open issues to maintained forks, not here.

**Comment by regorxxx** [comment]
Have updated the methods to support it.

**Comment by gka** [comment]
fwiw, this will also land in the original chroma.js soon 👋

**Comment by gka** [comment]
will be resolved in #347

**Comment by gka** [comment]
this feature is shipped with version 3.0!
