### ISSUE TITLE
Question: Luminance function desaturates colors. Is it by design?

### ISSUE THREAD

**Issue by Siddhantmd** [gka/chroma.js#334]
I was working on generating color scales with specific luminance values, during which I found that the luminance function desaturates colors. 

For example, I have the following luminance values that I want in my color scale:

> 0: 0.006999999999999999
1: 0.028705077559631413
2: 0.06734518665406404
3: 0.124316794617859
4: 0.2006822101430693
5: 0.29731013608158574
6: 0.41494094204116627
7: 0.5542229103185277
8: 0.7157346487207483
9: 0.9000000000000001

In the image below, I created colors based on the original color and the above list of luminance values in two ways:
1. Using chroma.luminance()
2. Manipulating the 'lightness' value for the color in the HSL color space such that the resulting color matched the desired luminance. 
(Just to be clear, I know that lightness value of HSL color space is different from relative luminance.)

![image](https://github.com/gka/chroma.js/assets/22995848/0af22e59-872b-4879-8a59-6b4c39f45b6b)

Both scales have the same luminance values. But as you can see, the colors generated using chroma.luminance() are desaturated. Is that by design? If so, why?

**Comment by gka** [comment]
according to the docs, you can control the color space in which the `luminance()` setter will interpolate the color until it matches the desired luminance by passing the mode as second argument:

```js
chroma('aquamarine').luminance(0.5); // rgb
chroma('aquamarine').luminance(0.5, 'lab');
chroma('aquamarine').luminance(0.5, 'hsl');
```

however, while testing this I noticed a bug, which will get fixed with the next release (there's a bigger refactoring going on in #336 right now which will fix this)

**Comment by gka** [comment]
bug fix is here https://github.com/gka/chroma.js/commit/b65520226b8e468caa80eb263a9962a920ad1dcb#diff-afd79edee2da171af35c39532ae729f24997334e552c63121b49a9a4cc9b7f16
