### ISSUE TITLE
Discord invite in README is invalid

### ISSUE THREAD

**Issue by bakert** [gka/chroma.js#355]
<img width="540" alt="image" src="https://github.com/user-attachments/assets/52af6185-b8d7-45eb-96f9-8f07117329a0">

<img width="677" alt="image" src="https://github.com/user-attachments/assets/b30ac1f1-2c30-48f8-9da8-bab280076bf2">

**Comment by gka** [comment]
Ah I didn't realize the url invalidated after 7 days. This one won't: https://discord.gg/7fgurEqTRe
