### ISSUE TITLE
The Oklab transformation is not using the revised Lightness calculation described by Björn Ottosson

### ISSUE THREAD

**Issue by ericmelse** [gka/chroma.js#358]
Dear Chroma.js team,

While testing chroma.js it seems to me that the **Oklab** transformation is not using the revised Lightness calculation as 
described by Björn Ottosson in the section **Intermission - a new lightness estimate for Oklab** on his [webpage](https://bottosson.github.io/posts/colorpicker/#intermission---a-new-lightness-estimate-for-oklab).

For example, for the color RGB=[255,0,0] the current result value calculated by `chroma.js` is L=0.63, whereas it should be L=0.57, using the revised Oklab lightness estimate.

As this is a rather important issue, I kindly ask for an update of the Oklab transformation in Chroma.js so that the revised Lightness estimate is used instead of the previous formulation.

Note that for a proper implementation of the transformation of colors to Okhsv and Okhsl color spaces in chroma.js, you need the revised Lightness estimate as well.

Best regards,
Eric Melse

**Comment by gka** [comment]
chroma.js is using the reference implementation used by the [W3C](https://www.w3.org/TR/css-color-4/#ok-lab) which is also implemented in all modern web browsers. This way, you can be sure that a OkLab color exported as CSS string is showing up exactly like it's RGB equivalent.

I do not know the reasoning behind the W3Cs decision not to use the "revised" transformation you're citing, but unfortunately, I think they set the new de facto standard for OKLab and it would be strange if chroma.js would use a different implementation.

**Comment by gka** [comment]
I think [this is the discussion](https://github.com/w3c/csswg-drafts/issues/6642) between the W3C team and @bottoson, if you care to dive in deeper into the topic. But from skimming it, it appears they seemed to have reached some sort of consensus at the end, so I'm closing this issue if you don't mind.

**Comment by ericmelse** [comment]
Dear GKA,
Thank you for your answer and explanation.
Most kind to provide me with the reference behind this implementation.
Best,
Eric
