### ISSUE TITLE
domain with min and max the same number

### ISSUE THREAD

**Issue by sixinli** [gka/chroma.js#37]
for getColor in line 1045 to 1046 (https://github.com/gka/chroma.js/blob/master/chroma.js)
        t = f0 = (val - _min) / (_max - _min)
        t = Math.min(1, Math.max(0, t))

this fails sometimes when min and max of the domain is the same. For example, I have domain [1, 1], this return an undefined color when I do getColor(1). I am wondering is the domain supposed to be inclusive, or is it a bug?

**Comment by Nibbler999** [comment]
@gka I don't think this change is correct. It looks like you meant to replace the line but added one. It has no effect as it is.
