### ISSUE TITLE
generate temperature colors, e.g. chroma.temperature(5500) => hex(FFEFE6)

### ISSUE THREAD

**Issue by Pomax** [gka/chroma.js#51]
While perhaps a little esoteric, it would be super useful if chroma.js could generate the colors associated with black body radiation colors (mostly for doing white balancing). Being able to pull up the temperature colors like on https://en.wikipedia.org/w/index.php?title=Color_temperature#Categorizing_different_lighting would be pretty sweet

**Comment by gka** [comment]
interesting read http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/

**Comment by gka** [comment]
also there's an implementation here: https://github.com/neilbartlett/color-temperature

**Comment by Pomax** [comment]
nice find!

**Comment by gka** [comment]
added the following to chroma.js

```js
// get color from temperature
chroma.kelvin(5000).hex()  // '#ffe3cd'
// estimate temperature of colors
chroma('pink').kelvin() // 4945
chroma('white').kelvin() // 6524
chroma('lightblue').kelvin() // 11914
```
