### ISSUE TITLE
Size?

### ISSUE THREAD

**Issue by qrohlf** [gka/chroma.js#54]
Am I missing something? The readme claims that chroma.js is 8.5kB, but it appears to be nearly four times that:

```
$ du -sh chroma.min.js
32K	/Users/qrohlf/Desktop/chroma.min.js
```

**Comment by blvz** [comment]
This is how you should measure it:

```sh
$ gzip -c chroma.min.js > chroma.min.js.gz
$ du -sh chroma.min.js.gz
 12K	chroma.min.js.gz
```

See: http://en.wikipedia.org/wiki/HTTP_compression

**Comment by qrohlf** [comment]
Ah, didn't realize you were measuring the gzipped size.

**Comment by blvz** [comment]
Actually, I'm not the creator, just a fellow user. Haha.
Most libraries specifies only the gzipped size and some, both.
