### ISSUE TITLE
Mix Function

### ISSUE THREAD

**Issue by jacobp100** [gka/chroma.js#59]
Rather than make a scale and specify the point, it would be nice to do `c1.mix(c2, [value: 0.5])`.

**Comment by gka** [comment]
in chroma that function exists, but it's called interpolate.

```js
chroma('red').interpolate(0.5, 'blue').hex() // "#7f007f"
```

Agree that ``mix`` would be a nice alias.

**Comment by gka** [comment]
Also this is being around for a while: 

```js
chrma.mix('red', 'blue', 0.25) // '#bf003f'
```
