### ISSUE TITLE
HCL (or LCH) value ranges

### ISSUE THREAD

**Issue by automata** [gka/chroma.js#63]
To calculate histograms, should I expect the following value ranges?

- H: `[0, 360]`
- C: ?
- L: `[0, 100]`

What's the value range/domain for Chroma?

**Comment by mcstone** [comment]
For colors you can display, the range for C will depend on H, L and the specific display calibration used to generate the HCL spec (usuall sRGB). For sRGB, max C is around 134, at RGB = 0,0255.

**Comment by gka** [comment]
thx @mcstone

**Comment by automata** [comment]
Thank you @mcstone !
