### ISSUE TITLE
`chroma(255,255,255,1).hsv()`faild convert to rgb? 

### ISSUE THREAD

**Issue by w88975** [gka/chroma.js#72]
``` javascript

chroma(255,255,255,1).hsv() // result: [NaN, 0, 1]

```

**Comment by gka** [comment]
you call `.hsv()`, so chroma will convert the color to HSV, so the result is [hue, sat, value]. hue is NaN because white has no hue. don't see a bug here.

**Comment by w88975** [comment]
@gka  I think `chroma(255,255,255,1).hsv()` should be `[0, 0, 1]`

**Comment by gka** [comment]
no, I don't agree. ``rgb(255,255,255)`` is a pure white that has no hue, whereas a hue of 0 degree represents a red tone. If a color has no hue at all, it makes sense to represent its hue as something different than ``0``, and with chroma.js I chose ``NaN``.  This has implications for the interpolation of colors. If the you want a gradient between white and green, you clearly don't want the hue to rotate from green to red, but to stay fixed at the green hue.
