### ISSUE TITLE
colorscale with limits gives same color for last 2 limit values

### ISSUE THREAD

**Issue by benib** [gka/chroma.js#80]
I use `limits()` to generate logarithmic classes for a colorscale.
getting a value from the scale gives the same color for the last 2 classes.

see this jsbin for the code: http://jsbin.com/hitunuquye/1/edit?html,console

Do I use this wrong somehow? I expect only the last color to be the upper bound of the colorscale.

**Comment by gka** [comment]
Yes that is correct. `scale.classes` sets the outer limits of each class. If you provide 5 numbers, you end up with 4 distinct colors. Feel free to check the [interactive example](http://gka.github.io/chroma.js/#scale-classes).

So in your example, you should compute the colors at the class center:
```
for (var i = 0; i < limits.length-1; i++) {
    // get colors at center of each class 
    console.log((limits[i] + limits[i+1])*0.5, scale(limits[i]).hex());
}
```
