### ISSUE TITLE
Unit Tests for Converters

### ISSUE THREAD

**Issue by hastebrot** [gka/chroma.js#84]
I couldn't find any unit tests for the modules in `src/converters/*`. Is there any need for them? 

Also: Would be interesting to see the HSI values with which the converter has problems (see: known issues from `README.md`).

**Comment by hastebrot** [comment]
We could test conversions from/to sRGB between the 16 basic W3C HTML 4.01 colors.

- http://www.w3.org/TR/css3-color/#html4
- https://en.wikipedia.org/wiki/Web_colors#HTML_color_names

**Comment by gka** [comment]
good idea (sorry for late reply)

added: https://github.com/gka/chroma.js/blob/master/test/converters-test.coffee
