### ISSUE TITLE
Docs: Bounds of LCH

### ISSUE THREAD

**Issue by hastebrot** [gka/chroma.js#85]
The docs state (http://gka.github.io/chroma.js/#chroma-lch):

> ### chroma.lch
> 
> **L**: Lightness, **c**: chroma (0-1), **h**: hue (0-1).
> 
> ```
> chroma.lch(80, 40, 130);
> chroma(80, 40, 130, 'lch');
> ```

But it seems that hue must be in 0..360 (instead of 0..1), and lightness and chroma in 0..100 (instead of 0..1).

**Comment by gka** [comment]
fixed
