### ISSUE TITLE
Property to check if color is clipped or not

### ISSUE THREAD

**Issue by ericvoid** [gka/chroma.js#86]
Your pickers and palette generators can detect when a color is clipped. Is there a property or method to check it?

**Comment by gka** [comment]
unfortunately this information gets lost the way chroma.js is currently set up. I agree it would be nice to keep it as something like `color.isClipped()`.

**Comment by gka** [comment]
added `color.clipped()` in 1.3.1.

see documentation https://gka.github.io/chroma.js/#color-clipped
