### ISSUE TITLE
HCG color space

### ISSUE THREAD

**Issue by ghost** [gka/chroma.js#88]
I sended pull request with HCG color model. Hue, Chrome, Grayscale (Gradient). 
Difference from HSL - L always change color, in HCG, G channel changes gray color of HSL. HCG does not support L. Instead of use combination of C and G.

Official repository: 
https://github.com/acterhd/hcg

Pull request: 
https://github.com/gka/chroma.js/pull/101 (complete)

**Comment by gka** [comment]
thanks for submitting the PR. I took a look at the implementation and tested the colorpicker you made using you hcg code. would you mind explaining a real-world use case for this color space? 

Also, in the [shader demo](https://www.shadertoy.com/view/ltSXRV) you say "As you can see, gray and chroma have difference.". Would you mind explaining the difference to me a little bit?

**Comment by acterhd** [comment]
HCG square, HSV triangle, HSL diamond form.

**Comment by acterhd** [comment]
I think this color space can be used in design, in science. This is convertable (polymorph) color space.

**Comment by acterhd** [comment]
Close this.
